#!/bin/bash
set -x

sudo ip netns add t1
sudo ip netns exec t1 ip link set dev lo up
sudo ip link add veth1a type veth peer name veth1b
sudo ip link set veth1b netns t1
sudo ip netns exec t1 ip addr add 10.0.0.2/24 dev veth1b
sudo ip netns exec t1 ip link set veth1b up

sudo ip link set veth1a up
sudo ip addr add 10.0.0.1/24 dev veth1a

sudo ip netns exec t1 \
    unshare --pid --mount-proc --fork \
    unshare --mount \
    "${@:-bash}"

sudo ip netns del t1
